#!/bin/bash
# ============================================================
#  Feint VPN Node — one-command installer
#  Usage:
#    curl -fsSL https://raw.githubusercontent.com/Feint-VPN/feint-node/main/install.sh | bash -s -- \
#        --domain vpn.example.com \
#        --email  admin@example.com
#
#  All flags:
#    --domain   FQDN that points to this server  (required)
#    --email    Let's Encrypt contact email      (required)
#    --secret   API secret key                   (default: random 32-char)
#    --api-port HTTPS API port                   (default: 8337)
#    --dir      Install directory                (default: /opt/vpn-node)
#    --sub      Enable subscription endpoint     (default: true)
#    --branch   Git branch to clone              (default: main)
# ============================================================
set -euo pipefail

# ── colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${BLUE}ℹ${NC}  $*"; }
success() { echo -e "${GREEN}✓${NC}  $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✗${NC}  $*" >&2; }
die()     { error "$*"; exit 1; }
header()  {
    echo ""
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}${CYAN}  $*${NC}"
    echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

# ── parse arguments ───────────────────────────────────────────────────────────
DOMAIN=""
EMAIL=""
API_SECRET=""
API_PORT="8337"
INSTALL_DIR="/opt/vpn-node"
SUB_ENABLED="true"
BRANCH="main"
NODE_IMAGE="ghcr.io/feint-vpn/feint-node:latest"
SINGBOX_IMAGE="ghcr.io/feint-vpn/feint-sing-box:v1.13.12-feint.1"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain)   DOMAIN="$2";      shift 2 ;;
        --email)    EMAIL="$2";       shift 2 ;;
        --secret)   API_SECRET="$2";  shift 2 ;;
        --api-port) API_PORT="$2";    shift 2 ;;
        --dir)      INSTALL_DIR="$2"; shift 2 ;;
        --sub)      SUB_ENABLED="$2"; shift 2 ;;
        --branch)   BRANCH="$2";      shift 2 ;;
        -h|--help)
            echo "Usage: $0 --domain <fqdn> --email <email> [options]"
            echo ""
            echo "  --domain   FQDN pointing to this server (required)"
            echo "  --email    Let's Encrypt contact email  (required)"
            echo "  --secret   API secret key               (auto-generated)"
            echo "  --api-port HTTPS API port               (default: 8337)"
            echo "  --dir      Install directory            (default: /opt/vpn-node)"
            echo "  --sub      Enable subscription endpoint (default: true)"
            echo "  --branch   Git branch                   (default: main)"
            exit 0 ;;
        *) die "Unknown argument: $1" ;;
    esac
done

# ── validate required args ────────────────────────────────────────────────────
[[ -z "$DOMAIN" ]] && die "--domain is required"
[[ -z "$EMAIL"  ]] && die "--email is required"

echo "$DOMAIN" | grep -qE '^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)+$' \
    || die "Invalid domain: $DOMAIN"
echo "$EMAIL" | grep -qE '^[^@]+@[^@]+\.[^@]+$' \
    || die "Invalid email: $EMAIL"
echo "$API_PORT" | grep -qE '^[0-9]{2,5}$' \
    || die "Invalid port: $API_PORT"

# ── must run as root ──────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && die "Run as root: sudo bash $0 $*"

# Installation is intentionally one-shot. Existing runtime state belongs to
# update.sh and must never be regenerated by this script.
if [[ -f "$INSTALL_DIR/.env.local" ]]; then
    die "Node already installed at $INSTALL_DIR. Run: sudo bash $INSTALL_DIR/update.sh"
fi

# ── banner ────────────────────────────────────────────────────────────────────
if [[ -t 1 && -n "${TERM:-}" ]]; then
    clear
fi
echo -e "${BOLD}${CYAN}"
cat << 'BANNER'
  ███████╗███████╗██╗███╗   ██╗████████╗
  ██╔════╝██╔════╝██║████╗  ██║╚══██╔══╝
  █████╗  █████╗  ██║██╔██╗ ██║   ██║
  ██╔══╝  ██╔══╝  ██║██║╚██╗██║   ██║
  ██║     ███████╗██║██║ ╚████║   ██║
  ╚═╝     ╚══════╝╚═╝╚═╝  ╚═══╝   ╚═╝
          VPN Node — one-command installer
BANNER
echo -e "${NC}"
echo -e "  ${BOLD}Domain:${NC}   $DOMAIN"
echo -e "  ${BOLD}Email:${NC}    $EMAIL"
echo -e "  ${BOLD}API port:${NC} $API_PORT"
echo -e "  ${BOLD}Install:${NC}  $INSTALL_DIR"
echo ""

# ── detect OS ────────────────────────────────────────────────────────────────
if [[ -f /etc/os-release ]]; then
    # shellcheck source=/dev/null
    source /etc/os-release
    OS_ID="${ID:-unknown}"
    OS_VER="${VERSION_ID:-0}"
else
    OS_ID="unknown"
fi

info "Detected OS: ${OS_ID} ${OS_VER}"

# ── helpers ───────────────────────────────────────────────────────────────────

# Generate a cryptographically secure random string
gen_secret() {
    local len="${1:-32}"
    local secret
    set +o pipefail
    if command -v openssl &>/dev/null; then
        secret="$(openssl rand -base64 $((len * 3 / 4 + 1)) | tr -dc 'A-Za-z0-9' | head -c "$len")"
    else
        secret="$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$len")"
    fi
    set -o pipefail
    printf '%s' "$secret"
}

# Stream command output without hiding its exit status.
run() {
    "$@" 2>&1 | sed 's/^/  │ /'
}

wait_for_runtime() {
    local url="$1"
    local response
    for _ in {1..30}; do
        response="$(curl -skf -H "X-API-Secret: ${API_SECRET}" "$url" || true)"
        if grep -q '"configuration":"available"' <<< "$response" \
            && grep -q '"sing_box":"running"' <<< "$response"; then
            return 0
        fi
        sleep 1
    done
    return 1
}

wait_for_status() {
    local url="$1"
    for _ in {1..30}; do
        curl -skf -H "X-API-Secret: ${API_SECRET}" "$url" \
            | grep -q '"status":"ok"' && return 0
        sleep 1
    done
    return 1
}

# ── step 1: install system packages ──────────────────────────────────────────
header "Step 1 / 6 — System packages"

export DEBIAN_FRONTEND=noninteractive

apt_install() {
    run apt-get install -y --no-install-recommends "$@"
}

info "Updating package index..."
run apt-get update

for pkg in curl git ca-certificates gnupg lsb-release openssl iproute2; do
    if ! dpkg -s "$pkg" &>/dev/null; then
        info "Installing $pkg..."
        apt_install "$pkg"
    fi
done
success "System packages ready"

# ── step 2: install docker ────────────────────────────────────────────────────
header "Step 2 / 6 — Docker"

if command -v docker &>/dev/null && docker compose version &>/dev/null; then
    success "Docker $(docker --version | cut -d' ' -f3 | tr -d ',') already installed"
else
    info "Installing Docker..."
    run bash -c "curl -fsSL https://get.docker.com | sh"
    systemctl enable docker --now >/dev/null 2>&1 || true
    success "Docker installed"
fi

# Ensure docker group exists (some images expect GID 987)
if ! getent group docker &>/dev/null; then
    groupadd docker
fi
DOCKER_GID=$(getent group docker | cut -d: -f3)
info "Docker GID: ${DOCKER_GID}"

# ── step 3: clone repository ──────────────────────────────────────────────────
header "Step 3 / 6 — Clone repository"

REPO_URL="https://github.com/Feint-VPN/feint-node.git"

if [[ -d "$INSTALL_DIR/.git" ]]; then
    warn "Directory $INSTALL_DIR already exists — pulling latest changes"
    run git -C "$INSTALL_DIR" fetch origin "$BRANCH" --progress
    run git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
else
    info "Cloning $REPO_URL → $INSTALL_DIR ..."
    run git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR" --progress
fi
success "Repository ready at $INSTALL_DIR"

# ── step 4: generate configuration ───────────────────────────────────────────
header "Step 4 / 6 — Generate configuration"

cd "$INSTALL_DIR"

ENV_FILE="$INSTALL_DIR/.env.local"
source "$INSTALL_DIR/scripts/lib/ports.sh"
if [[ ! -f "$ENV_FILE" ]]; then
    [[ -f .env.example ]] && cp .env.example "$ENV_FILE"
    [[ ! -f "$ENV_FILE" ]] && touch "$ENV_FILE"
fi

# Generate API secret if not provided
[[ -z "$API_SECRET" ]] && API_SECRET="$(gen_secret 32)"

# Generate all cryptographic material locally
#   Reality x25519 key pair — use sing-box container for guaranteed format
info "Generating x25519 key pair for Reality..."
KEYGEN_OUT="$(docker run --rm "$SINGBOX_IMAGE" generate reality-keypair)" \
    || die "Could not generate Reality keys with $SINGBOX_IMAGE"
REALITY_PRIVATE="$(awk '$1 == "PrivateKey:" { print $2; exit }' <<< "$KEYGEN_OUT")"
[[ -n "$REALITY_PRIVATE" ]] || die "sing-box returned no Reality private key"

REALITY_SHORT_ID=$(openssl rand -hex 8)

#   Shadowsocks 2022 PSK (32 bytes for aes-256)
SS_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')
SS_METHOD="2022-blake3-aes-256-gcm"
REALITY_SERVER_NAME="www.microsoft.com"
CLASH_API_SECRET=$(gen_secret 32)

#   Random VPN ports
info "Checking and selecting ports..."
port_require_available tcp "$API_PORT" "API_PORT" || die "Choose another --api-port value"
VLESS_PORT=$(port_find_free_unique tcp 10000 60000 "$API_PORT") || die "Could not find a free VLESS TCP port"
VMESS_PORT=$(port_find_free_unique tcp 10000 60000 "$API_PORT" "$VLESS_PORT") || die "Could not find a free VMess TCP port"
TROJAN_PORT=$(port_find_free_unique tcp 10000 60000 "$API_PORT" "$VLESS_PORT" "$VMESS_PORT") || die "Could not find a free Trojan TCP port"
HY2_PORT=$(port_find_free_unique udp 10000 60000) || die "Could not find a free Hysteria2 UDP port"
SS_PORT=$(port_find_free_unique tcp 10000 60000 "$API_PORT" "$VLESS_PORT" "$VMESS_PORT" "$TROJAN_PORT") || die "Could not find a free Shadowsocks TCP port"

# Detect public IP
SERVER_IP=$(curl -4sSf https://api.ipify.org 2>/dev/null \
         || curl -4sSf https://ifconfig.me 2>/dev/null \
         || ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' \
         || echo "0.0.0.0")

info "Detected public IP: $SERVER_IP"

# Write .env.local
info "Writing $ENV_FILE ..."
cat > "$ENV_FILE" << EOF
# Generated by install.sh on $(date -u '+%Y-%m-%d %H:%M UTC')

# API Settings
API_SECRET=${API_SECRET}
API_PORT=${API_PORT}
API_USE_SSL=true
HIDE_ENDPOINTS=true
DEV_MODE=false

# Server Settings
SERVER_DOMAIN=${DOMAIN}
SERVER_IP=${SERVER_IP}

# SSL/TLS Settings
TLS_ENABLED=true
TLS_CERT_PATH=/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
TLS_KEY_PATH=/etc/letsencrypt/live/${DOMAIN}/privkey.pem
CERTBOT_EMAIL=${EMAIL}
CERTBOT_PORT=80

# VPN Protocol Ports
VLESS_PORT=${VLESS_PORT}
VMESS_PORT=${VMESS_PORT}
TROJAN_PORT=${TROJAN_PORT}
HYSTERIA2_PORT=${HY2_PORT}
SHADOWSOCKS_PORT=${SS_PORT}

# Reality Settings (VLESS)
REALITY_PRIVATE_KEY=${REALITY_PRIVATE}
REALITY_SHORT_ID=${REALITY_SHORT_ID}
REALITY_SERVER_NAME=${REALITY_SERVER_NAME}

# Shadowsocks Settings
SHADOWSOCKS_PASSWORD=${SS_PASSWORD}
SHADOWSOCKS_METHOD=${SS_METHOD}

# Hysteria2 Bandwidth
HYSTERIA2_UP_MBPS=1000
HYSTERIA2_DOWN_MBPS=1000
CLASH_API_SECRET=${CLASH_API_SECRET}
CLASH_API_URL=http://host.docker.internal:9090
V2RAY_API_ADDRESS=host.docker.internal:10085

# Subscription
SUBSCRIPTION_ENABLED=${SUB_ENABLED}
SUB_URI_TEMPLATE=🌌 Feint | {Protocol}

# Logging
LOG_LEVEL=info
LOG_FORMAT=json

# Docker
NODE_IMAGE=${NODE_IMAGE}
SINGBOX_IMAGE=${SINGBOX_IMAGE}
DOCKER_SOCKET=/var/run/docker.sock
DOCKER_GID=${DOCKER_GID}
SINGBOX_CONTAINER_NAME=sing-box
CERTBOT_CONTAINER_NAME=certbot

# Paths
CONFIG_PATH=/opt/sing-box/config.json
BACKUP_DIR=/opt/sing-box/backups
EOF

success "Configuration written"

# Allow the API container's appuser (uid 1000) to write this file later
chown 1000:1000 "$ENV_FILE" 2>/dev/null || true

COMPOSE_PROJECT=$(basename "$INSTALL_DIR")
COMPOSE_CERT_VOL="${COMPOSE_PROJECT}_certbot-certs"
COMPOSE_CERT_WWW_VOL="${COMPOSE_PROJECT}_certbot-www"
COMPOSE_SINGBOX_VOL="${COMPOSE_PROJECT}_sing-box-data"

# ── step 5: obtain TLS certificate ───────────────────────────────────────────
header "Step 5 / 6 — TLS certificate"

# Port 80 must be free for the ACME standalone challenge
port_require_available tcp 80 "ACME standalone challenge" \
    || die "Port 80 is occupied. Stop or reconfigure the existing web server, or add a webroot/DNS ACME mode."

info "Issuing certificate for ${DOMAIN} via Let's Encrypt..."
docker volume create "${COMPOSE_CERT_VOL}" >/dev/null 2>&1 || true
docker volume create "${COMPOSE_CERT_WWW_VOL}" >/dev/null 2>&1 || true
docker run --rm \
    -p 80:80 \
    -v "${COMPOSE_CERT_VOL}:/etc/letsencrypt" \
    -v "${COMPOSE_CERT_WWW_VOL}:/var/www/certbot" \
    certbot/certbot certonly \
        --standalone \
        --non-interactive \
        --agree-tos \
        --email "$EMAIL" \
        --domains "$DOMAIN" \
        --preferred-challenges http \
        2>&1 | grep -E "(Congratulations|error|Error|Failed|Successfully|Cert)" || true

CERT_PATH="/var/lib/docker/volumes/${COMPOSE_CERT_VOL}/_data/live/${DOMAIN}/fullchain.pem"
if [[ -f "$CERT_PATH" ]]; then
    success "Certificate obtained for ${DOMAIN}"

    # The API container runs as appuser uid=1000, so make the issued certs
    # readable inside the compose volume mounted at /etc/letsencrypt.
    info "Fixing certificate permissions in ${COMPOSE_CERT_VOL}..."
    docker run --rm \
        --entrypoint sh \
        -v "${COMPOSE_CERT_VOL}:/certs" \
        certbot/certbot -c "chmod -R a+r /certs \
            && find /certs -type d -exec chmod a+x {} +" >/dev/null
    success "Certificates are ready in ${COMPOSE_CERT_VOL}"
else
    warn "Certificate not yet available — disabling SSL for initial startup."
    warn "Make sure your DNS A record for ${DOMAIN} points to ${SERVER_IP}"
    # Disable SSL in .env.local so uvicorn starts instead of crashing on
    # a missing cert file.  Re-enable after the cert is issued:
    #   sed -i 's/^TLS_ENABLED=.*/TLS_ENABLED=true/' .env.local
    #   sed -i 's/^API_USE_SSL=.*/API_USE_SSL=true/' .env.local
    #   docker compose restart vpn-node-api
    env_set "TLS_ENABLED"  "false" "$ENV_FILE"
    env_set "API_USE_SSL"  "false" "$ENV_FILE"
fi

# ── step 6: build and start containers ───────────────────────────────────────
header "Step 6 / 6 — Start containers"

# Compose reads API_PORT and DOCKER_GID from the declarative .env.local file.
compose() { docker compose --env-file "$ENV_FILE" "$@"; }

info "Pulling service images..."
run compose pull vpn-node-api sing-box

# ── render and validate sing-box config.json ──────────────────────────────────
info "Generating sing-box config.json..."

SINGBOX_TEMPLATE="$INSTALL_DIR/templates/sing-box.json.tpl"
SINGBOX_CONFIG="/tmp/singbox-install-config.json"
[[ -f "$SINGBOX_TEMPLATE" ]] || die "Missing sing-box template: $SINGBOX_TEMPLATE"

rendered_config=$(<"$SINGBOX_TEMPLATE")
replace_config_value() {
    local name="$1" value="$2"
    rendered_config=${rendered_config//"{{$name}}"/$value}
}

replace_config_value DOMAIN "$DOMAIN"
replace_config_value VLESS_PORT "$VLESS_PORT"
replace_config_value VMESS_PORT "$VMESS_PORT"
replace_config_value TROJAN_PORT "$TROJAN_PORT"
replace_config_value HYSTERIA2_PORT "$HY2_PORT"
replace_config_value SHADOWSOCKS_PORT "$SS_PORT"
replace_config_value REALITY_SERVER_NAME "$REALITY_SERVER_NAME"
replace_config_value REALITY_PRIVATE_KEY "$REALITY_PRIVATE"
replace_config_value REALITY_SHORT_ID "$REALITY_SHORT_ID"
replace_config_value SHADOWSOCKS_METHOD "$SS_METHOD"
replace_config_value SHADOWSOCKS_PASSWORD "$SS_PASSWORD"
replace_config_value CLASH_API_SECRET "$CLASH_API_SECRET"

printf '%s\n' "$rendered_config" > "$SINGBOX_CONFIG"
if grep -qE '\{\{[A-Z0-9_]+\}\}' "$SINGBOX_CONFIG"; then
    die "Unresolved value in sing-box template"
fi

info "Validating sing-box config..."
if ! compose run --rm --no-deps \
    -v "$SINGBOX_CONFIG:/tmp/config.json:ro" \
    sing-box check -c /tmp/config.json </dev/null; then
    die "Generated sing-box config is invalid"
fi

docker volume create "${COMPOSE_SINGBOX_VOL}" >/dev/null 2>&1 || true
docker run --rm \
    -v "${COMPOSE_SINGBOX_VOL}:/opt/sing-box" \
    -v "/tmp:/tmp" \
    alpine sh -c "mkdir -p /opt/sing-box && cp $SINGBOX_CONFIG /opt/sing-box/config.json && chown -R 1000:1000 /opt/sing-box"

info "Starting all containers..."
compose up -d --no-build

info "Waiting for VPN services to start..."
STATUS_SCHEME=https
[[ "$(env_get API_USE_SSL "$ENV_FILE" true)" == true ]] || STATUS_SCHEME=http
STATUS_URL="${STATUS_SCHEME}://127.0.0.1:${API_PORT}/status"
wait_for_runtime "$STATUS_URL" \
    || die "Containers started, but configuration or sing-box is unavailable"
success "Node runtime is ready"

# ── MTU TCPMSS clamp (fix for providers with reduced path MTU) ────────────────
info "Applying MTU TCPMSS clamp for NAT forwarding..."
_NIC=$(ip route get 8.8.8.8 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}' | head -1)
_NIC="${_NIC:-eth0}"
iptables -t mangle -C FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1380 2>/dev/null || \
    iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1380
iptables -t mangle -C POSTROUTING -o "$_NIC" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1380 2>/dev/null || \
    iptables -t mangle -A POSTROUTING -o "$_NIC" -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1380
# Persist across reboots via iptables-persistent
if ! dpkg -s iptables-persistent >/dev/null 2>&1; then
    echo iptables-persistent iptables-persistent/autosave_v4 boolean true | debconf-set-selections >/dev/null 2>&1 || true
    echo iptables-persistent iptables-persistent/autosave_v6 boolean false | debconf-set-selections >/dev/null 2>&1 || true
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q iptables-persistent >/dev/null 2>&1 || true
fi
if dpkg -s iptables-persistent >/dev/null 2>&1; then
    mkdir -p /etc/iptables
    iptables-save > /etc/iptables/rules.v4
    netfilter-persistent save >/dev/null 2>&1 || true
else
    warn "Could not install iptables-persistent — MTU clamp will not persist across reboot."
fi

header "Secure host"
"$INSTALL_DIR/scripts/setup-firewall.sh" --dir "$INSTALL_DIR"
wait_for_status "$STATUS_URL" \
    || die "Host was secured, but the complete node status is not healthy"
success "API status is healthy"

# ── summary ───────────────────────────────────────────────────────────────────
header "🎉  Installation complete"

echo -e "  ${BOLD}API URL:${NC}"
echo -e "    https://${DOMAIN}:${API_PORT}"
echo ""
echo -e "  ${BOLD}API credentials:${NC}"
echo -e "    Stored privately in ${ENV_FILE}"
echo ""
echo -e "  ${BOLD}VPN Ports:${NC}"
echo -e "    VLESS+Reality  → ${VLESS_PORT}/TCP"
echo -e "    VMess+WS+TLS  → ${VMESS_PORT}/TCP"
echo -e "    Trojan         → ${TROJAN_PORT}/TCP"
echo -e "    Hysteria2      → ${HY2_PORT}/UDP"
echo -e "    Shadowsocks    → ${SS_PORT}/TCP"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo ""
echo -e "  ${CYAN}# Create a user${NC}"
echo -e "  curl -sk -X POST https://${DOMAIN}:${API_PORT}/user \\"
echo -e "    -H 'X-API-Secret: <read it from .env.local>' \\"
echo -e "    -H 'Content-Type: application/json' \\"
echo -e "    -d '{\"username\": \"alice\"}'"
echo ""
echo -e "  ${CYAN}# Get Hiddify subscription URL${NC}"
echo -e "  curl -sk -H 'X-API-Secret: <read it from .env.local>' \\"
echo -e "    'https://${DOMAIN}:${API_PORT}/sub/alice?server_domain=${DOMAIN}'"
echo ""
echo -e "  ${CYAN}# Check container status${NC}"
echo -e "  docker compose -f ${INSTALL_DIR}/docker-compose.yml ps"
echo ""
echo -e "  ${BOLD}Config file:${NC} ${INSTALL_DIR}/.env.local"
echo -e "  ${BOLD}Logs:${NC}        docker compose -f ${INSTALL_DIR}/docker-compose.yml logs -f"
echo ""
warn "Keep ${ENV_FILE} private: it contains the API credentials."
echo ""
